#!/bin/bash
# Test: zet generate's hook-shim generation (core/hooks-generator.sh)
#
# HONEST LIMITATION: these tests prove the generator emits syntactically-plausible files under
# the right conditions (marker present, script path parameterized correctly, stale files removed).
# They do NOT prove the emitted TypeScript compiles, or that Pi would load it and actually block a
# real tool call — that requires a live Pi session (see the manual verification steps in the
# obsidian-git-sync harness's implementation plan for this feature).
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../core/test-runner.sh"

GENERATOR="$SCRIPT_DIR/../core/hooks-generator.sh"

setup() {
    zet_test_setup
    export ZET_ROOT="$TEST_HOME/project"
    export ZET_PI_EXTENSIONS="$TEST_HOME/output/pi-extensions"
    mkdir -p "$ZET_ROOT" "$ZET_PI_EXTENSIONS"

    mkdir -p "$ZET_ROOT/scripts"
    cat > "$ZET_ROOT/scripts/fixture-bash.sh" <<'EOF'
#!/bin/bash
input="$(cat)"
case "$input" in
    *DANGER*) echo "danger-label"; exit 0 ;;
    *) exit 1 ;;
esac
EOF
    chmod +x "$ZET_ROOT/scripts/fixture-bash.sh"

    cat > "$ZET_ROOT/scripts/fixture-edit.sh" <<'EOF'
#!/bin/bash
exit 0
EOF
    chmod +x "$ZET_ROOT/scripts/fixture-edit.sh"
}

teardown() {
    zet_test_teardown
}

echo "=== Test: hooks-generator ==="
echo ""

# --- bash_command shape generates a shim with the marker + script path ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
out="$ZET_PI_EXTENSIONS/fixture-bash.ts"
assert_file_exists "$out" "bash_command shim file created"
assert_contains "$out" "Generated by Zet" "shim carries the Zet marker"
assert_contains "$out" "$ZET_ROOT/scripts/fixture-bash.sh" "shim references the fixture script's absolute path"
assert_contains "$out" 'event.toolName !== "bash"' "bash_command shim narrows to bash tool calls"
teardown

# --- edit_write_content shape generates a shim with the marker + script path ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-edit]
source = "scripts/fixture-edit.sh"
targets = ["pi"]
pi_input_shape = "edit_write_content"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
out="$ZET_PI_EXTENSIONS/fixture-edit.ts"
assert_file_exists "$out" "edit_write_content shim file created"
assert_contains "$out" "Generated by Zet" "shim carries the Zet marker"
assert_contains "$out" "$ZET_ROOT/scripts/fixture-edit.sh" "shim references the fixture script's absolute path"
assert_contains "$out" 'tool_name: event.toolName === "write" ? "Write" : "Edit"' "shim capitalizes tool_name for the bash script's case-sensitive match"
teardown

# --- targets = [] produces no file ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-none]
source = "scripts/fixture-bash.sh"
targets = []
note = "documentation-only for this test"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-none.ts" "targets=[] entry produces no shim file"
teardown

# --- removing a [hooks.<name>] entry removes its stale generated shim ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "shim exists before entry is removed"
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.other]
source = "scripts/fixture-edit.sh"
targets = []
note = "unrelated entry, fixture-bash entry deliberately removed"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "stale shim removed after its zet.toml entry is deleted"
teardown

# --- unknown pi_input_shape warns and writes no file ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bogus]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bogus_shape"
EOF
warn_output="$(bash "$GENERATOR" --quiet 2>&1)"
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-bogus.ts" "unknown pi_input_shape writes no file"
assert_contains_str "$warn_output" "unknown pi_input_shape" "unknown pi_input_shape prints a WARNING"
teardown

# --- hand-written .ts (no Zet marker) is never touched by stale cleanup ---
setup
cat > "$ZET_PI_EXTENSIONS/hand-written.ts" <<'EOF'
// A real hand-authored extension, not generated by Zet.
export default function () {}
EOF
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.unrelated]
source = "scripts/fixture-bash.sh"
targets = []
note = "unrelated entry so hand-written.ts has no matching [hooks.hand-written]"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_exists "$ZET_PI_EXTENSIONS/hand-written.ts" "hand-written .ts without the Zet marker survives stale cleanup"
teardown

# --- targets pi but [paths].pi-extensions unset warns, writes nothing ---
setup
unset ZET_PI_EXTENSIONS
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
warn_output="$(bash "$GENERATOR" --quiet 2>&1)"
assert_contains_str "$warn_output" "pi-extensions is not configured" "unset pi-extensions path prints a WARNING, not a silent no-op"
teardown

# --- Codex-confirmed HIGH: deleting the LAST [hooks.*] table must still remove stale shims ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "shim exists before zet.toml's only [hooks.*] table is deleted"
: > "$ZET_ROOT/zet.toml"
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "stale shim removed even when zet.toml has ZERO [hooks.*] tables left"
teardown

# --- Codex-confirmed HIGH: an entry that regresses to invalid (still targets pi, source now
# missing) must not preserve its OLD generated shim — "targets pi" alone is not "successfully
# generated"; cleanup must track real generation success, not merely the targets field. ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "shim exists before its source is renamed away"
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/does-not-exist.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "old shim removed after its entry regresses to a missing source (still targets pi)"
teardown

# --- Codex-confirmed HIGH: hook names with their own dot (matching config.sh's validation
# grammar) must actually be discovered and generate a shim, not silently skipped. ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.release.guard]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_exists "$ZET_PI_EXTENSIONS/release.guard.ts" "dotted hook name (matching validate's own grammar) is discovered and generates a shim"
teardown

# --- Codex-confirmed MEDIUM: targets must be matched as exact tokens, not a *pi* substring ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["opencode-pi-bridge"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
assert_file_not_exists "$ZET_PI_EXTENSIONS/fixture-bash.ts" "a target NAME containing the substring 'pi' (not the exact token) is not treated as targeting pi"
teardown

# --- Codex-confirmed MEDIUM: a resolved script path containing a double-quote/backslash must
# not corrupt the generated TypeScript — the emitted SCRIPT_PATH must be a syntactically valid
# string literal whose value round-trips to the exact intended path. Exercised via ZET_ROOT
# itself containing a quote (a realistic vector: ANY absolute path under the project, not just
# `source`, gets interpolated as SCRIPT_PATH = "$ZET_ROOT/$source_rel"). ---
setup
weird_root="$TEST_HOME/weird\"root"
mkdir -p "$weird_root/scripts"
cp "$ZET_ROOT/scripts/fixture-bash.sh" "$weird_root/scripts/fixture-bash.sh"
ZET_ROOT="$weird_root" cat > "$weird_root/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
ZET_ROOT="$weird_root" bash "$GENERATOR" --quiet >/dev/null 2>&1
out="$ZET_PI_EXTENSIONS/fixture-bash.ts"
if [ -f "$out" ]; then
    python3 -c "
import re, sys
text = open('$out').read()
m = re.search(r'const SCRIPT_PATH = (.+);', text)
if not m:
    print('  FAIL: no SCRIPT_PATH line found in generated shim'); sys.exit(1)
import ast
try:
    # A syntactically valid double-quoted JS string literal is also valid as a Python literal
    # for this narrow escaping alphabet (both use backslash-escapes for quote/backslash).
    val = ast.literal_eval(m.group(1))
except Exception as e:
    print(f'  FAIL: SCRIPT_PATH is not a syntactically valid string literal: {m.group(1)!r} ({e})'); sys.exit(1)
if 'weird\"root' not in val:
    print(f'  FAIL: escaped value lost the original path content: {val!r}'); sys.exit(1)
print('  PASS: a quote-containing resolved path is emitted as a valid, round-tripping string literal')
"
else
    echo "  FAIL: shim was not generated for the quote-containing-path fixture"
fi
teardown

# --- Codex-confirmed MEDIUM: targets = [] with no note prints a WARNING (documentation-only
# entries must justify themselves, per the schema's own requirement) ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-undocumented]
source = "scripts/fixture-bash.sh"
targets = []
EOF
warn_output="$(bash "$GENERATOR" --quiet 2>&1)"
assert_contains_str "$warn_output" "has no note" "targets=[] with no note prints a WARNING"
teardown

# --- Codex-confirmed HIGH: a spawnSync failure (null status) must fail CLOSED (block), not
# silently allow the tool call through — this is a real runtime-behavior claim, not just a
# textual grep, so exercise it via node against the actual generated shim body. ---
setup
cat > "$ZET_ROOT/zet.toml" <<EOF
[hooks.fixture-bash]
source = "scripts/fixture-bash.sh"
targets = ["pi"]
pi_input_shape = "bash_command"
EOF
bash "$GENERATOR" --quiet >/dev/null 2>&1
if command -v node >/dev/null 2>&1; then
    node -e "
      const fs = require('fs');
      const src = fs.readFileSync('$ZET_PI_EXTENSIONS/fixture-bash.ts', 'utf-8');
      if (!src.includes('result.status === null')) {
        console.log('  FAIL: generated shim has no null-status fail-closed guard');
        process.exit(1);
      }
      console.log('  PASS: generated bash_command shim contains a null-status fail-closed guard');
    "
else
    echo "  SKIP: node not available, cannot verify null-status guard at runtime"
fi
teardown

echo ""
echo "=== Results ==="
echo "  Total: $((ZET_TESTS_PASSED + ZET_TESTS_FAILED)) | Passed: $ZET_TESTS_PASSED | Failed: $ZET_TESTS_FAILED"
if [ "$ZET_TESTS_FAILED" -gt 0 ]; then
    echo -e "$ZET_FAILURES"
    exit 1
else
    echo "  All tests passed."
fi
