#!/bin/bash
# Test: zet generate
# Verifies the generator correctly builds skills, agents, and rules from templates
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../core/test-runner.sh"

GENERATOR="$SCRIPT_DIR/../core/generator.sh"

# --- Test helpers ---
setup() {
    zet_test_setup
    export ZET_ROOT="$TEST_HOME/project"
    export ZET_TEMPLATES="$ZET_ROOT/templates"
    export ZET_SKILLS="$TEST_HOME/output/skills"
    # ZET_SKILLS_LOCAL isolated here for EVERY test (not just the tier-specific ones) — without this, any
    # test that doesn't set it falls through to generator.sh's real default (~/.claude/skills-local) and the
    # suite corrupts the USER's real local skill set on every run (a stray test-fixture dir ended up there
    # after a suite run touched live output). Every test must be fully isolated, not just the ones that ask.
    export ZET_SKILLS_LOCAL="$TEST_HOME/output/skills-local"
    # backend: codex has NO live default (unlike skills-local) — unset it here so a test that forgets to
    # export ZET_SKILLS_CODEX itself just gets the feature-off no-op path, never a stray inherited value
    # from the calling shell.
    unset ZET_SKILLS_CODEX
    unset ZET_PI_PROMPTS
    # PI_SKILLS must be isolated like skills-local: the default is the REAL ~/.pi/agent/skills, and an
    # un-isolated test run would write model-visible stubs into the user's live Pi skill set.
    unset ZET_PI_SKILLS
    unset ZET_GENERATE_JOBS
    unset ZET_GENERATE_FORCE
    export ZET_AGENTS="$TEST_HOME/output/agents"
    export ZET_RULES="$TEST_HOME/output/rules"
    export ZET_MODEL_ROLES="$ZET_ROOT/model-roles.conf"
    export ZET_GENERATE_CACHE_DIR="$TEST_HOME/cache/generate"
    # Isolate the generator's concurrency lock (${TMPDIR:-/tmp}/zet-generate.lock) to this test's own tmp dir
    # so the test suite can never touch/rmdir a REAL zet generate lock if one happens to be held concurrently
    # by an actual session using this vault.
    export TMPDIR="$TEST_HOME/tmp"
    mkdir -p "$TMPDIR"

    export ZET_PI_PROMPTS="$TEST_HOME/output/pi-prompts"
    mkdir -p "$ZET_TEMPLATES" "$ZET_SKILLS" "$ZET_SKILLS_LOCAL" "$ZET_AGENTS" "$ZET_RULES" "$ZET_PI_PROMPTS"
    export ZET_PI_SKILLS="$TEST_HOME/output/pi-skills"
    mkdir -p "$ZET_PI_SKILLS"

    cat > "$ZET_MODEL_ROLES" <<'EOF'
audit=haiku
execute=sonnet
think=opus
pi_think=primary-think
pi_think_provider=github-copilot
pi_think_fallback_1=bedrock-think
pi_think_fallback_1_provider=amazon-bedrock
pi_think_fallback_2=fireworks-think
pi_think_fallback_2_provider=fireworks-ai
think_effort=high
EOF
}

teardown() {
    zet_test_teardown
}

run_gen() {
    bash "$GENERATOR" --quiet 2>&1
}

mtime_seconds() {
    stat -f %m "$1" 2>/dev/null || stat -c %Y "$1"
}

# --- Tests ---

echo "=== Test: zet generate ==="
echo ""

# Test 1: Skill generation
echo "--- Skill generation ---"
setup
cat > "$ZET_TEMPLATES/hello_prompt_template.md" <<'EOF'
---
type: skill
description: A hello skill
---
# Hello content
EOF
output=$(run_gen)

assert_file_exists "$ZET_SKILLS/hello/SKILL.md" "skill created"
assert_contains "$ZET_SKILLS/hello/SKILL.md" "name: hello" "has name"
assert_contains "$ZET_SKILLS/hello/SKILL.md" 'description: "A hello skill"' "has description"
assert_contains "$ZET_SKILLS/hello/SKILL.md" "Generated by Zet" "has marker"
teardown

# Test 2: Agent generation
echo ""
echo "--- Agent generation ---"
setup
cat > "$ZET_TEMPLATES/reviewer_prompt_template.md" <<'EOF'
---
type: agent
description: Reviews code
model: sonnet
---
# Reviewer instructions
EOF
run_gen >/dev/null

assert_file_exists "$ZET_AGENTS/reviewer.md" "agent created"
assert_contains "$ZET_AGENTS/reviewer.md" "name: reviewer" "has injected name"
assert_not_contains "$ZET_AGENTS/reviewer.md" "^type:" "type stripped"
teardown

# Test 3: Rule generation
echo ""
echo "--- Rule generation ---"
setup
cat > "$ZET_TEMPLATES/style_prompt_template.md" <<'EOF'
---
type: rule
paths:
  - "src/**/*.ts"
---
# Style rules
EOF
run_gen >/dev/null

assert_file_exists "$ZET_RULES/style.md" "rule created"
assert_contains "$ZET_RULES/style.md" "paths:" "paths preserved"
assert_not_contains "$ZET_RULES/style.md" "^type:" "type stripped"
teardown

# Test 3b: Directory-scoped rules compile into AGENTS.md for AGENTS-native tools.
echo ""
echo "--- Directory rule AGENTS.md generation ---"
setup
mkdir -p "$ZET_ROOT/notes"
cat > "$ZET_TEMPLATES/note-format_prompt_template.md" <<'EOF'
---
type: rule
paths:
  - "notes/**/*.md"
---
# Note Format

Use short lines.
EOF
run_gen >/dev/null

assert_file_exists "$ZET_ROOT/notes/AGENTS.md" "directory rule AGENTS.md created"
assert_contains "$ZET_ROOT/notes/AGENTS.md" "Generated by Zet from path-scoped rules" "AGENTS.md is generated by Zet"
assert_contains "$ZET_ROOT/notes/AGENTS.md" "Use short lines." "rule content compiled into AGENTS.md"
teardown

# Test 4: Role resolution
echo ""
echo "--- Role resolution ---"
setup
cat > "$ZET_TEMPLATES/thinker_prompt_template.md" <<'EOF'
---
type: agent
role: think
---
# Deep thinker
EOF
run_gen >/dev/null

assert_contains "$ZET_AGENTS/thinker.md" "model: opus" "role resolved to model"
teardown

# Test 4b: Pi role chain and thinking frontmatter
echo ""
echo "--- Pi model fallback chain and thinking ---"
setup
cat > "$ZET_TEMPLATES/pi-thinker_prompt_template.md" <<'EOF'
---
type: skill
description: Pi thinking skill
role: think
---
# Pi thinker

Use the configured model chain.
EOF
run_gen >/dev/null

assert_file_exists "$ZET_PI_PROMPTS/pi-thinker.md" "Pi prompt created"
assert_not_contains "$ZET_PI_PROMPTS/pi-thinker.md" "^model:" "Pi prompt inherits session model (no frontmatter pin)"
assert_not_contains "$ZET_PI_PROMPTS/pi-thinker.md" "^thinking:" "Pi prompt inherits session thinking level"
assert_contains "$ZET_PI_PROMPTS/pi-thinker.md" "# Pi thinker" "template body preserved"
assert_file_exists "$ZET_PI_SKILLS/pi-thinker/SKILL.md" "Pi skill stub created"
assert_contains "$ZET_PI_SKILLS/pi-thinker/SKILL.md" "Generated by Zet" "Pi skill stub carries zet marker for stale cleanup"
assert_contains "$ZET_PI_SKILLS/pi-thinker/SKILL.md" "$ZET_PI_PROMPTS/pi-thinker.md" "Pi skill stub points at the generated prompt template"
assert_contains "$ZET_PI_SKILLS/pi-thinker/SKILL.md" "user-invocable: true" "Pi skill stub is model-visible"
assert_contains "$ZET_SKILLS/pi-thinker/SKILL.md" "model: opus" "Claude skill remains role-resolved"
teardown

# Test 4c: Duplicate model-role keys remain scalar
# A malformed or hand-merged model-roles.conf must not produce invalid YAML frontmatter.
echo ""
echo "--- Duplicate model-role keys ---"
setup
cat >> "$ZET_MODEL_ROLES" <<'EOF'
pi_think=duplicate-think
pi_think_provider=duplicate-provider
EOF
cat > "$ZET_TEMPLATES/pi-duplicate_prompt_template.md" <<'EOF'
---
type: skill
description: Pi duplicate key skill
role: think
---
# Pi duplicate key test
EOF
run_gen >/dev/null
assert_not_contains "$ZET_PI_PROMPTS/pi-duplicate.md" "^model:" "Pi prompt carries no model metadata (inherits session)"
teardown

# Test 5: Stale cleanup
echo ""
echo "--- Stale cleanup ---"
setup
mkdir -p "$ZET_SKILLS/stale-skill"
echo "<!-- Generated by Zet from stale-skill_prompt_template.md -->" > "$ZET_SKILLS/stale-skill/SKILL.md"
cat > "$ZET_TEMPLATES/live_prompt_template.md" <<'EOF'
---
type: skill
description: Still alive
---
# Live
EOF
run_gen >/dev/null

assert_dir_not_exists "$ZET_SKILLS/stale-skill" "stale skill removed"
assert_file_exists "$ZET_SKILLS/live/SKILL.md" "live skill kept"
teardown

# Test 6: Missing description skipped
echo ""
echo "--- Missing description ---"
setup
cat > "$ZET_TEMPLATES/nodesc_prompt_template.md" <<'EOF'
---
type: skill
---
# No description
EOF
output=$(run_gen)

assert_file_not_exists "$ZET_SKILLS/nodesc/SKILL.md" "no-desc skill skipped"
teardown

# Test 7: Dry run
echo ""
echo "--- Dry run ---"
setup
cat > "$ZET_TEMPLATES/drytest_prompt_template.md" <<'EOF'
---
type: skill
description: Dry test
---
# Content
EOF
bash "$GENERATOR" --dry --quiet >/dev/null 2>&1

assert_file_not_exists "$ZET_SKILLS/drytest/SKILL.md" "dry run writes nothing"
teardown

# Test 8: Follow instruction uses absolute path
echo ""
echo "--- Follow instruction uses absolute path ---"
setup
cat > "$ZET_TEMPLATES/abspath_prompt_template.md" <<'EOF'
---
type: skill
description: Tests absolute path in follow
---
# Content
EOF
run_gen >/dev/null

# The follow line must be an absolute path (starts with /) because
# SKILL.md lives in ~/.claude/skills/ — relative paths would break
follow_line=$(grep "^follow " "$ZET_SKILLS/abspath/SKILL.md")
assert_output_contains "$follow_line" "^follow /" "follow instruction is absolute path"
teardown

# Test 9: Prompt field self-reference stripping (renumbered)
echo ""
echo "--- Prompt field self-reference stripping ---"
setup
cat > "$ZET_TEMPLATES/stripper_prompt_template.md" <<EOF
---
type: skill
description: Tests prompt stripping
prompt: follow $ZET_TEMPLATES/stripper_prompt_template.md\nMode: full
---
# Stripper content
EOF
run_gen >/dev/null

# Should contain the extra args but not a duplicate follow line
assert_contains "$ZET_SKILLS/stripper/SKILL.md" "Mode: full" "prompt extra preserved"
teardown

# Test 9: Prompt field with no self-reference kept as-is
echo ""
echo "--- Prompt field non-self-reference kept ---"
setup
cat > "$ZET_TEMPLATES/custom_prompt_template.md" <<'EOF'
---
type: skill
description: Custom prompt
prompt: Do something special
---
# Custom
EOF
run_gen >/dev/null

assert_contains "$ZET_SKILLS/custom/SKILL.md" "Do something special" "custom prompt preserved"
teardown

# Test 10: Legacy AUTO-GENERATED marker files are preserved (not owned by zet)
echo ""
echo "--- Legacy marker preserved ---"
setup
mkdir -p "$ZET_SKILLS/legacy-skill"
echo "<!-- AUTO-GENERATED from legacy-skill_prompt_template.md -->" > "$ZET_SKILLS/legacy-skill/SKILL.md"
cat > "$ZET_TEMPLATES/live_prompt_template.md" <<'EOF'
---
type: skill
description: Still alive
---
# Live
EOF
run_gen >/dev/null

assert_dir_exists "$ZET_SKILLS/legacy-skill" "legacy marker skill preserved"
assert_file_exists "$ZET_SKILLS/live/SKILL.md" "live skill kept"
teardown

# Test 11: Non-generated files not cleaned up
echo ""
echo "--- Non-generated files preserved ---"
setup
mkdir -p "$ZET_SKILLS/manual-skill"
echo "# Hand-crafted skill" > "$ZET_SKILLS/manual-skill/SKILL.md"
cat > "$ZET_TEMPLATES/another_prompt_template.md" <<'EOF'
---
type: skill
description: Another
---
# Another
EOF
run_gen >/dev/null

assert_dir_exists "$ZET_SKILLS/manual-skill" "manual skill preserved"
teardown

# Test 12: DEFAULT tier is local — a skill with no tier: field lands in BOTH the full set and the local-tier
# plugin set (ccl should run all skills by default; tier: full-only is the explicit opt-out).
echo ""
echo "--- Default tier is local (no tier: field needed) ---"
setup
export ZET_SKILLS_LOCAL="$TEST_HOME/output/skills-local"
mkdir -p "$ZET_SKILLS_LOCAL"
cat > "$ZET_TEMPLATES/notier_prompt_template.md" <<'EOF'
---
type: skill
role: execute
description: no explicit tier
---
# No tier field
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS/notier/SKILL.md" "no-tier skill still in full set"
assert_file_exists "$ZET_SKILLS_LOCAL/skills/notier/SKILL.md" "no-tier skill DEFAULTS into the local set"
assert_file_exists "$ZET_SKILLS_LOCAL/.claude-plugin/plugin.json" "local plugin manifest emitted"
teardown

# Test 13: tier: full-only opts a skill OUT of the local set (full set unaffected)
echo ""
echo "--- tier: full-only excludes a skill from the local set ---"
setup
export ZET_SKILLS_LOCAL="$TEST_HOME/output/skills-local"
mkdir -p "$ZET_SKILLS_LOCAL"
cat > "$ZET_TEMPLATES/fullonly_prompt_template.md" <<'EOF'
---
type: skill
role: think
tier: full-only
description: must never appear locally
---
# Full-only
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS/fullonly/SKILL.md" "full-only skill still in full set"
assert_file_not_exists "$ZET_SKILLS_LOCAL/skills/fullonly/SKILL.md" "full-only skill excluded from local set"
teardown

# Test 14: concurrent generate runs never corrupt the local set (the multi-session race this lock fixes)
echo ""
echo "--- Concurrent zet generate runs serialize, never corrupt output ---"
setup
export ZET_SKILLS_LOCAL="$TEST_HOME/output/skills-local"
mkdir -p "$ZET_SKILLS_LOCAL"
cat > "$ZET_TEMPLATES/concur_prompt_template.md" <<'EOF'
---
type: skill
role: execute
description: concurrency probe
---
# Concur
EOF
for _ in 1 2 3; do run_gen >/dev/null & done
wait
assert_file_exists "$ZET_SKILLS_LOCAL/skills/concur/SKILL.md" "concurrent runs still produce the skill (no wipe-without-write corruption)"
teardown

# Test 15: the lock is STRICTLY ownership-scoped — a held lock actually BLOCKS a waiter (no steal), and the
# waiter proceeds only once the real holder releases it.
echo ""
echo "--- Lock blocks a waiter until the real holder releases (no steal) ---"
setup
export ZET_SKILLS_LOCAL="$TEST_HOME/output/skills-local"
mkdir -p "$ZET_SKILLS_LOCAL"
_LOCKDIR="${TMPDIR:-/tmp}/zet-generate.lock"
rmdir "$_LOCKDIR" 2>/dev/null || true
mkdir "$_LOCKDIR"                                  # simulate another process holding the lock
echo "$$" > "$_LOCKDIR/pid"                         # match generator.sh's lock contract
( sleep 2; rm -f "$_LOCKDIR/pid"; rmdir "$_LOCKDIR" 2>/dev/null ) &        # releases it after 2s — the waiter must not finish before this
_START=$(date +%s)
run_gen >/dev/null
_ELAPSED=$(( $(date +%s) - _START ))
wait
if [ "$_ELAPSED" -ge 2 ]; then
    zet_pass "waited for the real lock holder (${_ELAPSED}s >= 2s, no steal)"
else
    zet_fail "proceeded before the lock was released (${_ELAPSED}s < 2s) — possible steal"
fi
teardown

# Test 16: EVERY test is isolated from the user's REAL ~/.claude/skills-local, not just the ones that
# reference ZET_SKILLS_LOCAL explicitly. A plain run_gen (no per-test override, mirrors most of the suite's
# tests) must write into setup()'s isolated dir, never the real one — guards the exact leak that emptied the
# skill set (the suite ran with ZET_SKILLS_LOCAL unset in most tests, so it fell through to the live default).
echo ""
echo "--- Default ZET_SKILLS_LOCAL from setup() isolates every test, even without a per-test override ---"
setup
cat > "$ZET_TEMPLATES/isolcheck_prompt_template.md" <<'EOF'
---
type: skill
role: execute
description: isolation probe
---
# Isolation check
EOF
run_gen >/dev/null   # no explicit ZET_SKILLS_LOCAL export in this test body — setup() must have covered it
assert_file_exists "$ZET_SKILLS_LOCAL/skills/isolcheck/SKILL.md" "plain run_gen still isolated by setup()'s default"
teardown

# Test 17: configuring skills-codex means "project this skill set to Codex" — no per-template
# backend: codex tag required. This is the multi-harness SSOT behavior: paths select outputs.
echo ""
echo "--- skills-codex projects default skills to Codex ---"
setup
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
mkdir -p "$ZET_SKILLS_CODEX"
cat > "$ZET_TEMPLATES/nobackend_prompt_template.md" <<'EOF'
---
type: skill
description: no explicit backend
---
# No backend field
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS/nobackend/SKILL.md" "no-backend skill still in full set"
assert_file_exists "$ZET_SKILLS_CODEX/nobackend/SKILL.md" "no-backend skill gets a codex copy when skills-codex is configured"
teardown

# Test 18: Codex projection has no model: line (Codex has no per-skill model override — one global
# model in ~/.codex/config.toml). `backend: codex` remains accepted as a documentation annotation.
echo ""
echo "--- Codex projection omits model frontmatter ---"
setup
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
mkdir -p "$ZET_SKILLS_CODEX"
cat > "$ZET_TEMPLATES/codexskill_prompt_template.md" <<'EOF'
---
type: skill
role: execute
backend: codex
description: codex-backend skill
---
# Codex skill
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS/codexskill/SKILL.md" "codex-backend skill still in full Claude set"
assert_file_exists "$ZET_SKILLS_CODEX/codexskill/SKILL.md" "codex-backend skill mirrored into skills-codex"
if grep -q "^model:" "$ZET_SKILLS_CODEX/codexskill/SKILL.md"; then
    zet_fail "codex copy must never emit a model: line (Codex has no per-skill model override)"
else
    zet_pass "codex copy has no model: line"
fi
teardown

# Test 19: Codex projection is a NO-OP when skills-codex isn't configured. The output path is the
# opt-in; no Zet project writes into a real Codex directory accidentally.
echo ""
echo "--- Codex projection is a no-op with no skills-codex configured ---"
setup
# ZET_SKILLS_CODEX deliberately left unset (setup() already unsets it)
cat > "$ZET_TEMPLATES/codexnoop_prompt_template.md" <<'EOF'
---
type: skill
description: codex projection, no output dir configured
---
# Codex no-op
EOF
run_output=$(run_gen)
assert_file_exists "$ZET_SKILLS/codexnoop/SKILL.md" "skill still generated in full set"
if echo "$run_output" | grep -q "skills-codex"; then
    zet_fail "generator referenced skills-codex even though it isn't configured"
else
    zet_pass "no skills-codex reference when unconfigured"
fi
teardown

# Test 20: unknown backend value falls back to "claude" (full set) with a warning, rather than dropping
# the skill or crashing.
echo ""
echo "--- Unknown backend value falls back to claude with a warning ---"
setup
cat > "$ZET_TEMPLATES/badbackend_prompt_template.md" <<'EOF'
---
type: skill
backend: sparkles
description: bogus backend value
---
# Bad backend
EOF
run_output=$(run_gen)
assert_file_exists "$ZET_SKILLS/badbackend/SKILL.md" "bogus-backend skill still lands in the full set"
if echo "$run_output" | grep -q "unknown backend 'sparkles'"; then
    zet_pass "warns on unknown backend value"
else
    zet_fail "did not warn on unknown backend value"
fi
teardown

# Test 21: stale harness-specific generated outputs are removed without wiping the whole output dir.
echo ""
echo "--- Harness-specific stale outputs are removed ---"
setup
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
mkdir -p "$ZET_SKILLS_CODEX"
cat > "$ZET_TEMPLATES/retag_prompt_template.md" <<'EOF'
---
type: skill
role: think
description: starts projected to Codex
---
# Retag
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS_CODEX/retag/SKILL.md" "codex copy exists before retag"
assert_file_exists "$ZET_SKILLS_LOCAL/skills/retag/SKILL.md" "local copy exists before retag"
assert_file_exists "$ZET_PI_PROMPTS/retag.md" "Pi prompt exists before retag"
cat > "$ZET_TEMPLATES/retag_prompt_template.md" <<'EOF'
---
type: skill
codex: false
tier: full-only
description: retagged to skip Codex
---
# Retag
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS/retag/SKILL.md" "retagged skill still in full set"
assert_file_not_exists "$ZET_SKILLS_CODEX/retag/SKILL.md" "stale codex copy removed after retag"
assert_file_not_exists "$ZET_SKILLS_LOCAL/skills/retag/SKILL.md" "stale local copy removed after retag"
assert_file_not_exists "$ZET_PI_PROMPTS/retag.md" "stale Pi prompt removed after role removal"
assert_file_not_exists "$ZET_PI_SKILLS/retag/SKILL.md" "stale Pi skill stub removed after role removal"
teardown

# Test 22: hand-written skills mirrored into Codex also drop per-skill model frontmatter.
echo ""
echo "--- Hand-written Codex mirror strips model frontmatter ---"
setup
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
mkdir -p "$ZET_SKILLS/manualmode" "$ZET_SKILLS_CODEX"
cat > "$ZET_SKILLS/manualmode/SKILL.md" <<'EOF'
---
name: manualmode
description: Manual skill with model metadata
model: sonnet
---
# Manual
EOF
cat > "$ZET_TEMPLATES/live_prompt_template.md" <<'EOF'
---
type: skill
description: live template
---
# Live
EOF
run_gen >/dev/null
assert_file_exists "$ZET_SKILLS_CODEX/manualmode/SKILL.md" "hand-written skill mirrored into Codex"
assert_not_contains "$ZET_SKILLS_CODEX/manualmode/SKILL.md" "^model:" "hand-written Codex mirror strips model"
teardown

# Test 23: sibling skills render in bounded parallel jobs while preserving per-harness frontmatter.
echo ""
echo "--- Bounded parallel skill rendering preserves harness outputs ---"
setup
export ZET_GENERATE_JOBS=2
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
export ZET_AGENTS_STD="$TEST_HOME/output/agents-std"
mkdir -p "$ZET_SKILLS_CODEX" "$ZET_AGENTS_STD"
cat > "$ZET_TEMPLATES/alpha_prompt_template.md" <<'EOF'
---
type: skill
description: alpha parallel skill
role: think
---
# Alpha
EOF
cat > "$ZET_TEMPLATES/beta_prompt_template.md" <<'EOF'
---
type: skill
description: beta parallel skill
---
# Beta
EOF
parallel_output=$(bash "$GENERATOR" 2>&1)
assert_output_contains "$parallel_output" "Parallelism: 2 skill render job(s)" "reports configured parallelism"
assert_file_exists "$ZET_SKILLS/alpha/SKILL.md" "parallel alpha Claude skill created"
assert_file_exists "$ZET_SKILLS/beta/SKILL.md" "parallel beta Claude skill created"
assert_contains "$ZET_SKILLS/alpha/SKILL.md" "model: opus" "parallel full skill keeps role-resolved model"
assert_file_exists "$ZET_PI_PROMPTS/alpha.md" "parallel Pi prompt created"
assert_not_contains "$ZET_PI_PROMPTS/alpha.md" "^model:" "parallel Pi prompt inherits session model (no frontmatter pin)"
assert_file_exists "$ZET_AGENTS_STD/alpha/SKILL.md" "parallel interop skill created"
assert_file_exists "$ZET_SKILLS_CODEX/alpha/SKILL.md" "parallel Codex skill created"
assert_not_contains "$ZET_SKILLS_CODEX/alpha/SKILL.md" "^model:" "parallel Codex skill still omits model"
teardown

# Test 24: no-op generation compares and skips unchanged file replacement.
echo ""
echo "--- No-op generate preserves unchanged output mtimes ---"
setup
export ZET_GENERATE_JOBS=1
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
export ZET_AGENTS_STD="$TEST_HOME/output/agents-std"
mkdir -p "$ZET_SKILLS_CODEX" "$ZET_AGENTS_STD"
cat > "$ZET_TEMPLATES/cachecheck_prompt_template.md" <<'EOF'
---
type: skill
description: cache check
role: think
---
# Cache check
EOF
run_gen >/dev/null
full_file="$ZET_SKILLS/cachecheck/SKILL.md"
local_file="$ZET_SKILLS_LOCAL/skills/cachecheck/SKILL.md"
codex_file="$ZET_SKILLS_CODEX/cachecheck/SKILL.md"
pi_file="$ZET_PI_PROMPTS/cachecheck.md"
full_before=$(mtime_seconds "$full_file")
local_before=$(mtime_seconds "$local_file")
codex_before=$(mtime_seconds "$codex_file")
pi_before=$(mtime_seconds "$pi_file")
sleep 1
run_gen >/dev/null
assert_equals "$full_before" "$(mtime_seconds "$full_file")" "full skill mtime unchanged on no-op generate"
assert_equals "$local_before" "$(mtime_seconds "$local_file")" "local skill mtime unchanged on no-op generate"
assert_equals "$codex_before" "$(mtime_seconds "$codex_file")" "Codex skill mtime unchanged on no-op generate"
assert_equals "$pi_before" "$(mtime_seconds "$pi_file")" "Pi prompt mtime unchanged on no-op generate"
teardown

# Test 25: run-level cache skips only when the generated-output manifest still matches.
echo ""
echo "--- Run-level cache validates generated output manifest ---"
setup
export ZET_GENERATE_JOBS=1
export ZET_SKILLS_CODEX="$TEST_HOME/output/skills-codex"
mkdir -p "$ZET_SKILLS_CODEX"
cat > "$ZET_TEMPLATES/manifestcheck_prompt_template.md" <<'EOF'
---
type: skill
description: manifest cache check
role: think
---
# Manifest cache check
EOF
bash "$GENERATOR" >/dev/null 2>&1
cache_hit_output=$(bash "$GENERATOR" 2>&1)
assert_output_contains "$cache_hit_output" "Generated: skipped (cache hit)" "second unchanged run skips generation"

echo "# Manual drift" >> "$ZET_SKILLS/manifestcheck/SKILL.md"
drift_repair_output=$(bash "$GENERATOR" 2>&1)
assert_output_not_contains "$drift_repair_output" "cache hit" "edited generated file invalidates cache"
assert_not_contains "$ZET_SKILLS/manifestcheck/SKILL.md" "Manual drift" "edited generated file is repaired"

rm "$ZET_SKILLS_CODEX/manifestcheck/SKILL.md"
missing_repair_output=$(bash "$GENERATOR" 2>&1)
assert_output_not_contains "$missing_repair_output" "cache hit" "missing generated file invalidates cache"
assert_file_exists "$ZET_SKILLS_CODEX/manifestcheck/SKILL.md" "missing generated file is repaired"
teardown

zet_test_results
