#!/bin/bash
# Test: zet generate
# Verifies the generator correctly builds skills, agents, and rules from templates
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../core/test-runner.sh"

GENERATOR="$SCRIPT_DIR/../core/generator.sh"

# --- Test helpers ---
setup() {
    zet_test_setup
    export ZET_ROOT="$TEST_HOME/project"
    export ZET_TEMPLATES="$ZET_ROOT/templates"
    export ZET_SKILLS="$TEST_HOME/output/skills"
    export ZET_AGENTS="$TEST_HOME/output/agents"
    export ZET_RULES="$TEST_HOME/output/rules"
    export ZET_MODEL_ROLES="$ZET_ROOT/model-roles.conf"

    mkdir -p "$ZET_TEMPLATES" "$ZET_SKILLS" "$ZET_AGENTS" "$ZET_RULES"

    cat > "$ZET_MODEL_ROLES" <<'EOF'
audit=haiku
execute=sonnet
think=opus
EOF
}

teardown() {
    zet_test_teardown
}

run_gen() {
    bash "$GENERATOR" --quiet 2>&1
}

# --- Tests ---

echo "=== Test: zet generate ==="
echo ""

# Test 1: Skill generation
echo "--- Skill generation ---"
setup
cat > "$ZET_TEMPLATES/hello_prompt_template.md" <<'EOF'
---
type: skill
description: A hello skill
---
# Hello content
EOF
output=$(run_gen)

assert_file_exists "$ZET_SKILLS/hello/SKILL.md" "skill created"
assert_contains "$ZET_SKILLS/hello/SKILL.md" "name: hello" "has name"
assert_contains "$ZET_SKILLS/hello/SKILL.md" "description: A hello skill" "has description"
assert_contains "$ZET_SKILLS/hello/SKILL.md" "Generated by Zet" "has marker"
teardown

# Test 2: Agent generation
echo ""
echo "--- Agent generation ---"
setup
cat > "$ZET_TEMPLATES/reviewer_prompt_template.md" <<'EOF'
---
type: agent
description: Reviews code
model: sonnet
---
# Reviewer instructions
EOF
run_gen >/dev/null

assert_file_exists "$ZET_AGENTS/reviewer.md" "agent created"
assert_contains "$ZET_AGENTS/reviewer.md" "name: reviewer" "has injected name"
assert_not_contains "$ZET_AGENTS/reviewer.md" "^type:" "type stripped"
teardown

# Test 3: Rule generation
echo ""
echo "--- Rule generation ---"
setup
cat > "$ZET_TEMPLATES/style_prompt_template.md" <<'EOF'
---
type: rule
paths:
  - "src/**/*.ts"
---
# Style rules
EOF
run_gen >/dev/null

assert_file_exists "$ZET_RULES/style.md" "rule created"
assert_contains "$ZET_RULES/style.md" "paths:" "paths preserved"
assert_not_contains "$ZET_RULES/style.md" "^type:" "type stripped"
teardown

# Test 4: Role resolution
echo ""
echo "--- Role resolution ---"
setup
cat > "$ZET_TEMPLATES/thinker_prompt_template.md" <<'EOF'
---
type: agent
role: think
---
# Deep thinker
EOF
run_gen >/dev/null

assert_contains "$ZET_AGENTS/thinker.md" "model: opus" "role resolved to model"
teardown

# Test 5: Stale cleanup
echo ""
echo "--- Stale cleanup ---"
setup
mkdir -p "$ZET_SKILLS/stale-skill"
echo "<!-- Generated by Zet from stale-skill_prompt_template.md -->" > "$ZET_SKILLS/stale-skill/SKILL.md"
cat > "$ZET_TEMPLATES/live_prompt_template.md" <<'EOF'
---
type: skill
description: Still alive
---
# Live
EOF
run_gen >/dev/null

assert_dir_not_exists "$ZET_SKILLS/stale-skill" "stale skill removed"
assert_file_exists "$ZET_SKILLS/live/SKILL.md" "live skill kept"
teardown

# Test 6: Missing description skipped
echo ""
echo "--- Missing description ---"
setup
cat > "$ZET_TEMPLATES/nodesc_prompt_template.md" <<'EOF'
---
type: skill
---
# No description
EOF
output=$(run_gen)

assert_file_not_exists "$ZET_SKILLS/nodesc/SKILL.md" "no-desc skill skipped"
teardown

# Test 7: Dry run
echo ""
echo "--- Dry run ---"
setup
cat > "$ZET_TEMPLATES/drytest_prompt_template.md" <<'EOF'
---
type: skill
description: Dry test
---
# Content
EOF
bash "$GENERATOR" --dry --quiet >/dev/null 2>&1

assert_file_not_exists "$ZET_SKILLS/drytest/SKILL.md" "dry run writes nothing"
teardown

# Test 8: Follow instruction uses absolute path
echo ""
echo "--- Follow instruction uses absolute path ---"
setup
cat > "$ZET_TEMPLATES/abspath_prompt_template.md" <<'EOF'
---
type: skill
description: Tests absolute path in follow
---
# Content
EOF
run_gen >/dev/null

# The follow line must be an absolute path (starts with /) because
# SKILL.md lives in ~/.claude/skills/ — relative paths would break
follow_line=$(grep "^follow " "$ZET_SKILLS/abspath/SKILL.md")
assert_output_contains "$follow_line" "^follow /" "follow instruction is absolute path"
teardown

# Test 9: Prompt field self-reference stripping (renumbered)
echo ""
echo "--- Prompt field self-reference stripping ---"
setup
cat > "$ZET_TEMPLATES/stripper_prompt_template.md" <<EOF
---
type: skill
description: Tests prompt stripping
prompt: follow $ZET_TEMPLATES/stripper_prompt_template.md\nMode: full
---
# Stripper content
EOF
run_gen >/dev/null

# Should contain the extra args but not a duplicate follow line
assert_contains "$ZET_SKILLS/stripper/SKILL.md" "Mode: full" "prompt extra preserved"
teardown

# Test 9: Prompt field with no self-reference kept as-is
echo ""
echo "--- Prompt field non-self-reference kept ---"
setup
cat > "$ZET_TEMPLATES/custom_prompt_template.md" <<'EOF'
---
type: skill
description: Custom prompt
prompt: Do something special
---
# Custom
EOF
run_gen >/dev/null

assert_contains "$ZET_SKILLS/custom/SKILL.md" "Do something special" "custom prompt preserved"
teardown

# Test 10: Legacy AUTO-GENERATED marker files are preserved (not owned by zet)
echo ""
echo "--- Legacy marker preserved ---"
setup
mkdir -p "$ZET_SKILLS/legacy-skill"
echo "<!-- AUTO-GENERATED from legacy-skill_prompt_template.md -->" > "$ZET_SKILLS/legacy-skill/SKILL.md"
cat > "$ZET_TEMPLATES/live_prompt_template.md" <<'EOF'
---
type: skill
description: Still alive
---
# Live
EOF
run_gen >/dev/null

assert_dir_exists "$ZET_SKILLS/legacy-skill" "legacy marker skill preserved"
assert_file_exists "$ZET_SKILLS/live/SKILL.md" "live skill kept"
teardown

# Test 11: Non-generated files not cleaned up
echo ""
echo "--- Non-generated files preserved ---"
setup
mkdir -p "$ZET_SKILLS/manual-skill"
echo "# Hand-crafted skill" > "$ZET_SKILLS/manual-skill/SKILL.md"
cat > "$ZET_TEMPLATES/another_prompt_template.md" <<'EOF'
---
type: skill
description: Another
---
# Another
EOF
run_gen >/dev/null

assert_dir_exists "$ZET_SKILLS/manual-skill" "manual skill preserved"
teardown

zet_test_results
