#!/bin/bash
# Test: zet doctor
# Verifies health check detection of broken symlinks, stale paths,
# wiki links, rule paths, descriptions, roles, and secrets
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../core/test-runner.sh"

DOCTOR="$SCRIPT_DIR/../core/doctor.sh"

# --- Test helpers ---
setup() {
    zet_test_setup
    export ZET_ROOT="$TEST_HOME/project"
    export ZET_TEMPLATES="$ZET_ROOT/templates"
    export ZET_SKILLS="$TEST_HOME/output/skills"
    export ZET_AGENTS="$TEST_HOME/output/agents"
    export ZET_RULES="$TEST_HOME/output/rules"
    export ZET_MODEL_ROLES="$ZET_ROOT/model-roles.conf"
    export ZET_INSTRUCTION_FILES=""

    mkdir -p "$ZET_TEMPLATES" "$ZET_SKILLS" "$ZET_AGENTS" "$ZET_RULES"

    cat > "$ZET_ROOT/model-roles.conf" <<'EOF'
audit=haiku
execute=sonnet
think=opus
EOF
}

teardown() {
    zet_test_teardown
}

run_doctor() {
    bash "$DOCTOR" --quiet 2>&1 || true
}

run_doctor_json() {
    bash "$DOCTOR" --json 2>&1
}

# --- Tests ---

echo "=== Test: zet doctor ==="
echo ""

# Test 1: Clean project — no issues
echo "--- Clean project ---"
setup
# Override HOME to prevent doctor from checking real ~/.claude/CLAUDE.md
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/hello_prompt_template.md" <<'EOF'
---
type: skill
description: A valid skill
---
# Hello
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"total": 0' "clean project has zero issues"
teardown

# Test 2: Broken symlink detection
echo ""
echo "--- Broken symlinks ---"
setup
ln -s "/nonexistent/path" "$ZET_SKILLS/broken-link"
output=$(run_doctor_json)
assert_contains_str "$output" '"broken_symlinks"' "reports broken symlinks"
assert_not_contains_str "$output" '"total": 0' "total is nonzero"
teardown

# Test 3: Broken template reference detection
echo ""
echo "--- Broken template references ---"
setup
cat > "$ZET_TEMPLATES/linker_prompt_template.md" <<'EOF'
---
type: skill
description: Has template references
---
See [[nonexistent_prompt_template]] for details.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "nonexistent_prompt_template" "detects broken template reference"
teardown

# Test 4: Valid template reference not flagged
echo ""
echo "--- Valid template references ---"
setup
cat > "$ZET_TEMPLATES/target_prompt_template.md" <<'EOF'
---
type: skill
description: Target
---
# Target
EOF
cat > "$ZET_TEMPLATES/source_prompt_template.md" <<'EOF'
---
type: skill
description: Source references target
---
See [[target_prompt_template]] for details.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"broken_refs": []' "valid template references not flagged"
teardown

# Test 5: Rule missing paths
echo ""
echo "--- Rule missing paths ---"
setup
mkdir -p "$ZET_RULES"
cat > "$ZET_RULES/norule.md" <<'EOF'
---
name: norule
---
<!-- Generated by Zet from norule_prompt_template.md -->
# No paths field
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "norule.md" "detects rule without paths"
teardown

# Test 6: Rule with paths or global not flagged
echo ""
echo "--- Rule with paths not flagged ---"
setup
mkdir -p "$ZET_RULES"
cat > "$ZET_RULES/goodrule.md" <<'EOF'
---
name: goodrule
paths:
  - "src/**/*.ts"
---
<!-- Generated by Zet from goodrule_prompt_template.md -->
# Good rule
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"missing_rule_paths": []' "rule with paths not flagged"
teardown

# Test 7: Missing description detection
echo ""
echo "--- Missing description ---"
setup
cat > "$ZET_TEMPLATES/nodesc_prompt_template.md" <<'EOF'
---
type: skill
---
# No description
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "nodesc_prompt_template.md" "detects missing description"
teardown

# Test 8: Stale model role detection
echo ""
echo "--- Stale model roles ---"
setup
cat > "$ZET_TEMPLATES/badrole_prompt_template.md" <<'EOF'
---
type: agent
role: nonexistent
description: Has undefined role
---
# Bad role
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "nonexistent" "detects undefined role"
teardown

# Test 9: Secret detection
echo ""
echo "--- Secret detection ---"
setup
cat > "$ZET_TEMPLATES/leaky_prompt_template.md" <<'EOF'
---
type: skill
description: Has a secret
---
API_KEY=sk-abcdefghijklmnopqrstuvwxyz1234567890
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "leaky_prompt_template.md" "detects potential secret"
teardown

# Test 10: Stale paths in instruction files
echo ""
echo "--- Stale instruction paths ---"
setup
cat > "$ZET_ROOT/CLAUDE.md" <<'EOF'
Read ~/nonexistent/path/file.md for details.
Also check $HOME/another/missing.sh for info.
EOF
export ZET_INSTRUCTION_FILES="$ZET_ROOT/CLAUDE.md"
output=$(run_doctor_json)
assert_contains_str "$output" "stale_paths" "detects stale paths"
assert_not_contains_str "$output" '"stale_paths": []' "stale paths not empty"
teardown

# Test 11: Legacy marker (AUTO-GENERATED) in rules recognized
echo ""
echo "--- Legacy marker recognition ---"
setup
mkdir -p "$ZET_RULES"
cat > "$ZET_RULES/legacy.md" <<'EOF'
---
name: legacy
---
<!-- AUTO-GENERATED from legacy_prompt_template.md -->
# Legacy rule without paths
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "legacy.md" "recognizes legacy AUTO-GENERATED marker"
teardown

# Test 12: No model-roles file — reports all roles as stale
echo ""
echo "--- No model-roles file ---"
setup
rm -f "$ZET_ROOT/model-roles.conf"
cat > "$ZET_TEMPLATES/orphan_prompt_template.md" <<'EOF'
---
type: agent
role: think
description: Uses role but no conf file
---
# Orphan
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "no model-roles file" "reports missing model-roles"
teardown

# Test 13: No hardcoded paths in output
echo ""
echo "--- No hardcoded paths in output ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/safe_prompt_template.md" <<'EOF'
---
type: skill
description: Safe skill
---
# Content
EOF
output=$(run_doctor_json)
assert_not_contains_str "$output" "/Users/" "no hardcoded user paths in output"
assert_not_contains_str "$output" "/home/" "no hardcoded home paths in output"
assert_not_contains_str "$output" "CHANGEME" "no placeholder tokens in output"
teardown

# Test 14: Token bomb detection — unbounded fan-out in loop
echo ""
echo "--- Token bomb: unbounded fan-out ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/dangerous_prompt_template.md" <<'EOF'
---
type: skill
description: Dangerous unbounded fan-out
---
# Dangerous Skill

For each file in the repository, launch an Agent tool to review it.
Iterate over all items and spawn a subagent for processing.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "dangerous_prompt_template.md" "detects unbounded Agent fan-out"
assert_contains_str "$output" "HIGH" "rates unbounded fan-out as HIGH"
teardown

# Test 15: Token bomb — bounded fan-out is safe
echo ""
echo "--- Token bomb: bounded fan-out (safe) ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/safe_fanout_prompt_template.md" <<'EOF'
---
type: skill
description: Safe bounded fan-out
---
# Safe Skill

For each file, launch an Agent tool to review it.
Maximum 5 agents. Stop after 5 iterations.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"token_bombs": []' "bounded fan-out not flagged"
teardown

# Test 16: Token bomb — no fan-out at all is safe
echo ""
echo "--- Token bomb: no fan-out (safe) ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/normal_prompt_template.md" <<'EOF'
---
type: skill
description: Normal skill with no agents
---
# Normal Skill

Just do the thing. No agents involved.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"token_bombs": []' "no-agent template not flagged"
teardown

# Test 17: Token bomb — "loop" in prose without iteration context is safe
echo ""
echo "--- Token bomb: bare loop word (safe) ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/loopy_prompt_template.md" <<'EOF'
---
type: skill
description: Mentions loop but no iteration
---
# Feedback Loop Skill

Use the Agent tool to run a feedback loop.
The event loop handles this pattern well.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" '"token_bombs": []' "bare loop word not flagged as token bomb"
teardown

# Test 18: Token bomb — body with --- (horizontal rule) parsed correctly
echo ""
echo "--- Token bomb: body with --- separator ---"
setup
export HOME="$TEST_HOME"
cat > "$ZET_TEMPLATES/separator_prompt_template.md" <<'EOF'
---
type: skill
description: Has separator in body
---
# Intro

Some text above.

---

For each item, launch an Agent tool to process it.
Iterate through all results with a subagent.
EOF
output=$(run_doctor_json)
assert_contains_str "$output" "separator_prompt_template.md" "detects fan-out after --- in body"
teardown

zet_test_results
