#!/bin/bash
# Zet Hooks Generator — build Pi extension shims from [hooks.<name>] tables in zet.toml
# Usage: hooks-generator.sh [--dry] [--quiet]
# Dependencies: bash, grep, awk
#
# A [hooks.<name>] table names ONE existing gate script (bash, already wired into Claude Code's
# own .claude/settings.json hooks) and, if it opts in via `targets`, generates a thin TypeScript
# shim that shells out to that SAME script from inside a Pi coding-agent extension. This NEVER
# duplicates gate logic in TypeScript — every generated shim is a translator between Pi's
# tool_call event shape and the target script's existing stdin-JSON contract, nothing more.
#
# A [hooks.<name>] entry with targets = [] is a valid, intentional state (documentation-only —
# the hook cannot be ported yet, e.g. the target harness has no hook API, or the event shape
# needed doesn't exist). It requires a `note` explaining why, but generates no file.
# Supported Pi input shapes: bash_command and edit_write_content for tool_call (pre-tool), plus
# edit_write_post_content for tool_result (post-tool). Post-tool adapters are required for checks
# that inspect the file after Pi applies an edit; mapping those to tool_call changes their meaning.
#
# Environment variables (override zet.toml):
#   ZET_ROOT           — project root (default: current directory)
#   ZET_PI_EXTENSIONS  — Pi extension output dir (default: unset — feature off, no destructive
#                         default; a hook targeting pi with this unset is a loud WARNING, not a
#                         silent no-op, since a missing safety shim is a safety-relevant gap)
#   ZET_SESSION_BOARD  — path to a session-board.sh-shaped approval-state script (default: unset —
#                         optional; a bash_command shim passes its resolved absolute path through
#                         to the target script as _CCS_SESSION_BOARD env var ONLY if configured,
#                         so a project with no such script gets exactly today's behavior, no change)
#   ZET_GENERATE_CACHE_DIR — run-level cache dir (default: ~/.cache/zet/generate)
#   ZET_GENERATE_FORCE — set to 1 to bypass the run-level cache
set -e

ZET_ROOT="${ZET_ROOT:-$(pwd)}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"
source "$SCRIPT_DIR/frontmatter.sh"
zet_config_init "$ZET_ROOT"

DRY_RUN=false
QUIET=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry)   DRY_RUN=true; shift ;;
        --quiet) QUIET=true; shift ;;
        *) shift ;;   # ignore unknown args — generator.sh already validated the real CLI surface
    esac
done

_pi_extensions_raw="${ZET_PI_EXTENSIONS:-$(zet_config_get "paths" "pi-extensions" "")}"
PI_EXTENSIONS_DIR=""
[ -n "$_pi_extensions_raw" ] && PI_EXTENSIONS_DIR="$(resolve_path "$_pi_extensions_raw")"

_session_board_raw="${ZET_SESSION_BOARD:-$(zet_config_get "paths" "session-board" "")}"
SESSION_BOARD_PATH=""
[ -n "$_session_board_raw" ] && SESSION_BOARD_PATH="$(resolve_path "$_session_board_raw")"
GENERATE_CACHE_ROOT="${ZET_GENERATE_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/zet/generate}"
GENERATE_CACHE_KEY="$(printf '%s\nhooks' "$ZET_ROOT" | shasum | awk '{print $1}')"
HOOKS_CACHE_FILE="$GENERATE_CACHE_ROOT/$GENERATE_CACHE_KEY.hooks.sha"
HOOKS_MANIFEST_FILE="$GENERATE_CACHE_ROOT/$GENERATE_CACHE_KEY.hooks.manifest"
GENERATE_FORCE="${ZET_GENERATE_FORCE:-0}"
HOOKS_CACHEABLE=1

is_generated_file() {
    grep -q "Generated by Zet" "$1" 2>/dev/null
}

write_if_changed() {
    local target="$1" dir base tmp
    dir=$(dirname "$target")
    base=$(basename "$target")
    mkdir -p "$dir"
    if [ -f "$target" ] && ! is_generated_file "$target"; then
        echo "  ERROR: refusing to overwrite non-Zet extension: $target" >&2
        exit 1
    fi
    tmp="$dir/.$base.tmp.$$.$RANDOM"
    cat > "$tmp"
    if [ -f "$target" ] && cmp -s "$tmp" "$target"; then
        rm -f "$tmp"
    else
        mv "$tmp" "$target"
    fi
}

hash_file_or_missing() {
    local file="$1"
    if [ -f "$file" ]; then
        shasum "$file"
    else
        printf 'MISSING  %s\n' "$file"
    fi
}

hash_file_value() {
    shasum "$1" | awk '{print $1}'
}

# Token-aware check for "pi" as a declared target, not a substring match. `targets` is a TOML
# array rendered as a raw string like ["pi"] or [] by zet_config_get. A bare *pi* case-match
# would wrongly treat a hypothetical future target like "opencode-pi-bridge" as targeting pi —
# strip brackets/quotes/whitespace and compare each comma-separated token exactly.
_targets_has_pi() {
    local targets="$1" token
    targets="${targets#\[}"; targets="${targets%\]}"
    IFS=',' read -ra _tokens <<< "$targets"
    for token in "${_tokens[@]}"; do
        token="${token//\"/}"; token="${token//\'/}"
        token="${token#"${token%%[![:space:]]*}"}"; token="${token%"${token##*[![:space:]]}"}"
        [ "$token" = "pi" ] && return 0
    done
    return 1
}

# JSON-string-encode a value for safe embedding inside a generated .ts file's string/comment
# literals. Values interpolated into the heredocs below (hook name, resolved absolute script
# path) come from zet.toml free-text fields with no character restriction — an unescaped
# double-quote, backslash, or backtick could corrupt the emitted TypeScript (breaking out of a
# string literal or comment) rather than just producing a cosmetically odd file. python3 is
# already a dependency elsewhere in this codebase (scanner.sh's JSON output); reuse it here
# rather than hand-rolling shell string escaping, which is exactly the class of bug this guards
# against in the first place.
_ts_string_escape() {
    python3 -c 'import json, sys; print(json.dumps(sys.argv[1]))' "$1"
}

# --- Enumerate [hooks.<name>] section names ---
# core/config.sh has no "list all sections matching a prefix" primitive; a grep here is the
# smallest addition rather than growing config.sh for a single consumer (matches this repo's own
# "no premature abstraction" convention elsewhere in generator.sh). Matches config.sh's own
# validation grammar for dotted sections (each dot-separated segment is [a-zA-Z0-9_-]+) — a
# narrower discovery pattern here would silently skip a hook name that DID pass validation
# (e.g. a name containing its own dot, like "release.guard"), generating no shim for it with
# no warning at all.
hook_names=()
if [ -f "$ZET_CONFIG_FILE" ]; then
    while IFS= read -r name; do
        [ -n "$name" ] && hook_names+=("$name")
    done < <(grep -oE '^\[hooks\.[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)*\]' "$ZET_CONFIG_FILE" 2>/dev/null | sed -E 's/^\[hooks\.(.*)\]$/\1/')
fi

# NOTE: stale-shim cleanup (below) must run even when hook_names is empty — deleting the LAST
# [hooks.*] table from zet.toml is exactly the case where every previously generated shim needs
# to be removed, not left running with no corresponding config entry at all. Do not early-exit here.

compute_hooks_fingerprint() {
    local name section source_rel targets pi_input_shape note
    {
        printf 'zet-hooks-generate-v2\n'
        printf 'root=%s\n' "$ZET_ROOT"
        printf 'pi-extensions=%s\n' "$PI_EXTENSIONS_DIR"
        printf 'session-board=%s\n' "$SESSION_BOARD_PATH"
        hash_file_or_missing "$SCRIPT_DIR/hooks-generator.sh"
        hash_file_or_missing "$SCRIPT_DIR/config.sh"
        hash_file_or_missing "$ZET_CONFIG_FILE"
        [ -n "$SESSION_BOARD_PATH" ] && hash_file_or_missing "$SESSION_BOARD_PATH"
        printf 'hook-count=%s\n' "${#hook_names[@]}"
        for name in "${hook_names[@]}"; do
            section="hooks.$name"
            source_rel="$(zet_config_get "$section" "source" "")"
            targets="$(zet_config_get "$section" "targets" "")"
            pi_input_shape="$(zet_config_get "$section" "pi_input_shape" "")"
            note="$(zet_config_get "$section" "note" "")"
            printf 'hook=%s\tsource=%s\ttargets=%s\tshape=%s\tnote=%s\n' "$name" "$source_rel" "$targets" "$pi_input_shape" "$note"
            [ -n "$source_rel" ] && hash_file_or_missing "$ZET_ROOT/$source_rel"
        done
    } | shasum | awk '{print $1}'
}

hooks_cache_hit() {
    local fingerprint="$1" cached_fingerprint line expected path count=0
    local paths=() expected_lines="" expected_sorted actual_sorted
    [ "$GENERATE_FORCE" = "1" ] && return 1
    [ -f "$HOOKS_CACHE_FILE" ] && [ -f "$HOOKS_MANIFEST_FILE" ] || return 1
    cached_fingerprint=$(sed -n '1p' "$HOOKS_CACHE_FILE")
    [ "$cached_fingerprint" = "$fingerprint" ] || return 1

    while IFS= read -r line || [ -n "$line" ]; do
        [ -z "$line" ] && continue
        case "$line" in
            *$'\t'*)
                expected="${line%%$'\t'*}"
                path="${line#*$'\t'}"
                ;;
            *) return 1 ;;
        esac
        [ -f "$path" ] || return 1
        paths+=("$path")
        expected_lines="${expected_lines}${expected}  ${path}"$'\n'
        count=$((count + 1))
    done < "$HOOKS_MANIFEST_FILE"

    [ "$count" -eq 0 ] && return 0
    expected_sorted=$(printf '%s' "$expected_lines" | sort)
    actual_sorted=$(shasum "${paths[@]}" | sort)
    [ "$actual_sorted" = "$expected_sorted" ]
}

emit_manifest_entry() {
    local file="$1"
    [ -f "$file" ] || return 0
    printf '%s\t%s\n' "$(hash_file_value "$file")" "$file"
}

collect_hooks_manifest() {
    local ts_file
    [ -n "$PI_EXTENSIONS_DIR" ] && [ -d "$PI_EXTENSIONS_DIR" ] || return 0
    for ts_file in "$PI_EXTENSIONS_DIR"/*.ts; do
        [ -f "$ts_file" ] || continue
        is_generated_file "$ts_file" || continue
        emit_manifest_entry "$ts_file"
    done
}

save_hooks_cache() {
    local fp_tmp manifest_tmp
    $DRY_RUN && return 0
    [ "$HOOKS_CACHEABLE" -eq 1 ] || return 0
    if ! mkdir -p "$GENERATE_CACHE_ROOT"; then
        $QUIET || echo "  WARNING: could not write hooks cache dir: $GENERATE_CACHE_ROOT" >&2
        return 0
    fi

    fp_tmp="$HOOKS_CACHE_FILE.tmp.$$"
    manifest_tmp="$HOOKS_MANIFEST_FILE.tmp.$$"
    if ! printf '%s\n' "$CURRENT_HOOKS_FINGERPRINT" > "$fp_tmp"; then
        rm -f "$fp_tmp" "$manifest_tmp"
        $QUIET || echo "  WARNING: could not write hooks cache fingerprint" >&2
        return 0
    fi
    if ! collect_hooks_manifest | sort > "$manifest_tmp"; then
        rm -f "$fp_tmp" "$manifest_tmp"
        $QUIET || echo "  WARNING: could not write hooks cache manifest" >&2
        return 0
    fi
    mv "$fp_tmp" "$HOOKS_CACHE_FILE"
    mv "$manifest_tmp" "$HOOKS_MANIFEST_FILE"
}

CURRENT_HOOKS_FINGERPRINT=$(compute_hooks_fingerprint)
if ! $DRY_RUN && hooks_cache_hit "$CURRENT_HOOKS_FINGERPRINT"; then
    $QUIET || echo "Generated: skipped hook shims (cache hit)"
    exit 0
fi

emit_bash_command_shim() {
    # Parameterized version of the proven danger-scan.ts pattern: extract event.input.command for
    # a bash tool_call, pipe it to the target script's --why mode on stdin, translate its exit-code
    # verdict into Pi's {block, reason} shape.
    local name="$1" source_rel="$2" out_file="$3"
    local source_abs="$ZET_ROOT/$source_rel"
    # Hook names are already restricted to [a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)* by config.sh's own
    # section-header validation grammar (see discovery grep above), so $name is safe verbatim in
    # a // comment and as a plain string-literal segment. $source_rel is a free-text zet.toml
    # value with NO such restriction — a path containing a double-quote or backslash could break
    # out of the SCRIPT_PATH string literal and corrupt/redefine the emitted TypeScript. Encode it
    # as a proper JS string literal rather than interpolating raw text.
    local source_abs_js
    source_abs_js="$(_ts_string_escape "$source_abs")"
    # If [paths].session-board is configured, pass ctx.cwd + its resolved path through as env vars
    # the target script can OPT INTO checking (e.g. ccs-danger-scan.sh clears a plain "git push"
    # match if a live, sha-bound approval was explicitly recorded via session-board.sh
    # approve-push) — a real authorization channel, never a weaker text match. Left out entirely
    # when unconfigured, so a project with no such script gets exactly the prior spawnSync call,
    # unchanged.
    local env_block=""
    if [ -n "$SESSION_BOARD_PATH" ]; then
        local board_js
        board_js="$(_ts_string_escape "$SESSION_BOARD_PATH")"
        env_block="
      env: {
        ...process.env,
        _CCS_PUSH_APPROVAL_CWD: ctx.cwd,
        _CCS_SESSION_BOARD: $board_js,
      },"
    fi
    write_if_changed "$out_file" <<TSEOF
// Ports Claude Code's $name gate into Pi. Single source of truth stays
// $source_rel — this extension only translates Pi's tool_call (bash) shape
// into that script's stdin contract and relays its verdict.
// Generated by Zet from zet.toml [hooks.$name] — do not edit directly.
// Regenerate: zet generate
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";

const SCRIPT_PATH = $source_abs_js;

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName !== "bash") return;
    const command = (event.input as { command?: string }).command;
    if (!command) return;

    // Each source gate owns its stdin and exit-code contract. Danger scan receives the raw
    // command and returns exit 0 for dangerous; Claude-shaped gates receive hook JSON and return
    // exit 2 for a block. A generic --why/exit-2 adapter silently inverts these contracts.
    const sourceName = "$name";
    const dangerScan = sourceName === "danger-scan";
    const input = dangerScan
      ? command
      : JSON.stringify({
          tool_name: "Bash",
          tool_input: { command },
          cwd: ctx.cwd,
        });
    const args = dangerScan ? [SCRIPT_PATH, "--why"] : [SCRIPT_PATH];
    const result = spawnSync("bash", args, {
      input,
      encoding: "utf-8",$env_block
    });

    // result.status is null if spawnSync itself failed (missing bash binary, script deleted,
    // permission/resource error) — that is NOT the same as the script running and confirming
    // safety (status 1). Treat a null status as unverified and block, matching this project's
    // own fail-closed convention (ccs-permission-audit.sh's "a scanner outage never silently
    // passes as clean") rather than silently allowing the tool call through.
    if (result.status === null) {
      return { block: true, reason: "$name could not run (spawnSync failed) — failing closed, not auto-approving." };
    }
    // Bash gates use exit 2 for a genuine block and exit 0 for abstain/allow.
    // Treating exit 0 as a block makes every safe Pi Bash call fail closed with an empty reason.
    const blocked = dangerScan ? result.status === 0 : result.status === 2;
    if (blocked) {
      const why = result.stderr.trim() || result.stdout.trim();
      // Mirrors Claude Code's own PreToolUse permission prompt: a flagged command doesn't die
      // silently on a text reason — it puts up a real yes/no dialog right where the command was
      // about to run, so an explicit in-session choice clears the gate right where the command
      // was about to run. Only possible in UI-capable modes (interactive/RPC); print/json modes
      // have no dialog surface and keep the unconditional hard-block (ctx.hasUI is false there).
      // THREE options (Alice, ask-gap design): "Yes (run once)" approves this call only;
      // "Always yes" approves this call AND records a promotion signal — "I believe this is safe
      // for the auto-approver to approve in future" — via the ask-gap audit in
      // typing-aware-confirm.ts (it logs every select whose options include allow/always), later
      // mined by R-utils/scripts/ask-gap-review.sh review (frequency + read-only-ness + judge
      // verification decide promotion; the click itself NEVER changes any gate behavior).
      if (ctx.hasUI) {
        const choice = await ctx.ui.select(
          \`Blocked by $name\\n\\n\${command}\\n\\nMatched: \${why}\\n\\nRun anyway? — "Always yes" also records a signal that you consider this safe for the auto-approver to approve in future.\`,
          ["Yes (run once)", "No", "Always yes"],
        );
        if (choice === "Yes (run once)" || choice === "Always yes") return;
      }
      return { block: true, reason: \`Blocked by $name (matches: \${why}). Needs explicit approval.\` };
    }
  });
}
TSEOF
}

emit_edit_write_content_shim() {
    # Reconstructs the {tool_name, tool_input:{file_path, ...}} stdin JSON shape Claude Code's
    # own Edit|Write hooks already expect — the ONLY new code is this adapter; the target script
    # is unchanged. Capitalizes tool_name to "Edit"/"Write" (Pi's event.toolName is lowercase) —
    # required because these bash hooks case-sensitively match `case "$TOOL_NAME" in Edit|Write)`.
    local name="$1" source_rel="$2" out_file="$3"
    local source_abs="$ZET_ROOT/$source_rel"
    # See emit_bash_command_shim's comment: $source_rel is unrestricted free text, encode as a
    # real JS string literal rather than raw interpolation to avoid corrupting the generated file.
    local source_abs_js
    source_abs_js="$(_ts_string_escape "$source_abs")"
    write_if_changed "$out_file" <<TSEOF
// Ports Claude Code's $name gate into Pi. Single source of truth stays
// $source_rel — this extension only translates Pi's tool_call (edit/write) shape
// into that script's stdin JSON contract and relays its verdict.
// Generated by Zet from zet.toml [hooks.$name] — do not edit directly.
// Regenerate: zet generate
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";

const SCRIPT_PATH = $source_abs_js;

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    if (event.toolName !== "edit" && event.toolName !== "write") return;

    // event.toolName narrows CustomToolCallEvent-compatible unions poorly (its toolName is a bare
    // string, so === comparisons don't narrow event.input's type) — cast explicitly rather than
    // rely on TS narrowing here, same pattern the hand-written danger-scan.ts shim already uses.
    let toolInputJson: Record<string, unknown>;
    if (event.toolName === "write") {
      const input = event.input as { path: string; content: string };
      toolInputJson = { file_path: input.path, content: input.content };
    } else {
      // Pi's edit tool supports multiple {oldText,newText} pairs; the bash script's contract
      // only reads a single old_string/new_string pair. Concatenate — matches the script's own
      // intent of scanning the union of newly-written text, not a specific edit index.
      const input = event.input as { path: string; edits: { oldText: string; newText: string }[] };
      const oldText = input.edits.map((e) => e.oldText).join("\\n");
      const newText = input.edits.map((e) => e.newText).join("\\n");
      toolInputJson = { file_path: input.path, old_string: oldText, new_string: newText };
    }

    const payload = JSON.stringify({
      tool_name: event.toolName === "write" ? "Write" : "Edit",
      tool_input: toolInputJson,
    });
    const result = spawnSync("bash", [SCRIPT_PATH], { input: payload, encoding: "utf-8" });

    // See emit_bash_command_shim's identical comment: a null status means spawnSync itself
    // failed, not that the script ran and confirmed safety — fail closed, never silently allow.
    if (result.status === null) {
      return { block: true, reason: "$name could not run (spawnSync failed) — failing closed, not auto-approving." };
    }
    if (result.status === 2) {
      return { block: true, reason: result.stderr.trim() || \`Blocked by $name.\` };
    }
  });
}
TSEOF
}

emit_edit_write_post_content_shim() {
    # Runs after Pi has applied an edit/write, matching Claude's PostToolUse semantics.
    # The source script scans the resulting file, so this must not be emitted as tool_call.
    local name="$1" source_rel="$2" out_file="$3"
    local source_abs="$ZET_ROOT/$source_rel"
    local source_abs_js
    source_abs_js="$(_ts_string_escape "$source_abs")"
    write_if_changed "$out_file" <<TSEOF
// Ports Claude Code's $name post-tool hook into Pi. Single source of truth stays
// $source_rel — this extension only translates Pi's tool_result shape into the
// script's existing stdin JSON contract and relays its verdict.
// Generated by Zet from zet.toml [hooks.$name] — do not edit directly.
// Regenerate: zet generate
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";

const SCRIPT_PATH = $source_abs_js;

export default function (pi: ExtensionAPI) {
  pi.on("tool_result", async (event) => {
    if (event.toolName !== "edit" && event.toolName !== "write") return;

    let toolInput: Record<string, unknown>;
    if (event.toolName === "write") {
      const input = event.input as { path: string; content: string };
      toolInput = { file_path: input.path, content: input.content };
    } else {
      const input = event.input as { path: string; edits: { oldText: string; newText: string }[] };
      toolInput = {
        file_path: input.path,
        old_string: input.edits.map((edit) => edit.oldText).join("\\n"),
        new_string: input.edits.map((edit) => edit.newText).join("\\n"),
      };
    }

    const payload = JSON.stringify({
      tool_name: event.toolName === "write" ? "Write" : "Edit",
      tool_input: toolInput,
    });
    const result = spawnSync("bash", [SCRIPT_PATH], { input: payload, encoding: "utf-8", timeout: 10000 });

    // Installed Pi contract (runner.js emitToolResult): a tool_result handler returns a PARTIAL
    // PATCH of {content, details, isError, usage}; omitted fields keep their current values.
    // {block, reason} are silently IGNORED here — and this is POST-execution anyway: the edit
    // was already applied, so a diagnostic can inform the model/UI but can never undo or block
    // it. Blocking is the pre-tool gate's job (emit_bash_command_shim keeps {block, reason}).
    function appendDiagnostic(evt: { content?: unknown; isError?: boolean }, text: string, isError?: boolean) {
      // Append-only: preserve the original result content and error state, never overwrite.
      const block = { type: "text" as const, text };
      const patch: { content?: unknown; isError?: boolean } = {};
      if (Array.isArray(evt.content)) patch.content = [...evt.content, block];
      else if (typeof evt.content === "string" && evt.content.length > 0) patch.content = evt.content + "\\n" + text;
      else patch.content = [block];
      if (isError !== undefined) patch.isError = isError;
      else if (evt.isError) patch.isError = true; // preserve pre-existing error state
      return patch;
    }

    // Bounded diagnostic: a chatty source script must not flood the model context.
    const raw = ((result.stdout as string) || "").trim();
    const diag = raw.length > 2000 ? raw.slice(0, 2000) + "…(truncated)" : raw;

    if (result.status === null || result.error || result.signal) {
      // Operational failure (spawn failure, timeout kill, signal death). The edit is ALREADY
      // applied — surface the failure honestly; never pretend it blocked or reverted anything.
      const why = result.error ? (result.error as Error).message : result.signal ? \`killed by signal \${result.signal}\` : "spawnSync failed";
      return appendDiagnostic(event, \`$name could not run (\${why}) — the edit is already applied; the check did NOT complete and did NOT block it.\`, true);
    }
    if (result.status === 2) {
      // Policy violation found in the already-written file: bounded isError-marked diagnostic.
      // The file stays edited; a separate authoritative pre-tool gate owns real blocking.
      return appendDiagnostic(event, diag || \`$name found violations — the edit is already applied; correct the reported pointer.\`, true);
    }
    if (result.status !== 0) {
      // Unexpected exit code: operational error, never a silent allow and never a verdict.
      return appendDiagnostic(event, \`$name exited \${result.status} (unexpected) — the check did not complete; the edit is already applied.\`, true);
    }
    const nudge = ((result.stderr as string) || "").trim();
    if (nudge) {
      // Advisory exit-0 feedback (e.g. a due-date nudge on stderr): surface it WITHOUT isError.
      const bounded = nudge.length > 2000 ? nudge.slice(0, 2000) + "…(truncated)" : nudge;
      return appendDiagnostic(event, bounded, false);
    }
    return undefined; // clean run, nothing to say — leave the tool result untouched
  });
}
TSEOF
}

generated_count=0
doc_only_count=0
# Names that ended this run with a REAL, valid generated shim on disk — NOT merely "targets pi",
# since a pi-targeted entry can still fail to generate (missing source, unknown pi_input_shape,
# unconfigured output dir). Cleanup below must only spare files backed by this set; otherwise an
# entry that regresses to invalid (e.g. a renamed source, a retagged pi_input_shape) keeps its
# OLD, now-orphaned shim running forever just because `targets` still happens to say "pi".
valid_generated_names=()

for name in "${hook_names[@]}"; do
    section="hooks.$name"
    source_rel="$(zet_config_get "$section" "source" "")"
    targets="$(zet_config_get "$section" "targets" "")"
    pi_input_shape="$(zet_config_get "$section" "pi_input_shape" "")"
    note="$(zet_config_get "$section" "note" "")"

    if ! _targets_has_pi "$targets"; then
        doc_only_count=$((doc_only_count + 1))
        if [ -z "$note" ]; then
            HOOKS_CACHEABLE=0
            echo "  WARNING: [hooks.$name] targets = [] but has no note explaining why — documentation-only entries must justify themselves" >&2
        fi
        $QUIET || echo "  hook: $name (documentation-only, see zet.toml note)"
        continue
    fi

    if [ -z "$source_rel" ] || [ ! -f "$ZET_ROOT/$source_rel" ]; then
        HOOKS_CACHEABLE=0
        echo "  WARNING: [hooks.$name] source not found: $source_rel — skipping" >&2
        continue
    fi

    if [ -z "$PI_EXTENSIONS_DIR" ]; then
        HOOKS_CACHEABLE=0
        echo "  WARNING: [hooks.$name] targets pi but [paths].pi-extensions is not configured — skipping" >&2
        continue
    fi

    out_file="$PI_EXTENSIONS_DIR/$name.ts"

    case "$pi_input_shape" in
        bash_command)
            if ! $DRY_RUN; then
                mkdir -p "$PI_EXTENSIONS_DIR"
                emit_bash_command_shim "$name" "$source_rel" "$out_file"
            fi
            ;;
        edit_write_content)
            if ! $DRY_RUN; then
                mkdir -p "$PI_EXTENSIONS_DIR"
                emit_edit_write_content_shim "$name" "$source_rel" "$out_file"
            fi
            ;;
        edit_write_post_content)
            if ! $DRY_RUN; then
                mkdir -p "$PI_EXTENSIONS_DIR"
                emit_edit_write_post_content_shim "$name" "$source_rel" "$out_file"
            fi
            ;;
        *)
            HOOKS_CACHEABLE=0
            echo "  WARNING: [hooks.$name] unknown pi_input_shape '$pi_input_shape' — skipping" >&2
            continue
            ;;
    esac

    generated_count=$((generated_count + 1))
    valid_generated_names+=("$name")
    $QUIET || echo "  hook: $name (+pi, $pi_input_shape)"
done

# --- Cleanup stale generated shims ---
# A .ts file carrying the Zet marker whose hook entry is no longer a VALID pi-targeting entry
# (retagged, removed from zet.toml, or regressed to invalid — missing source, unknown shape, or
# unconfigured output dir) must not silently keep running as a live extension — mirrors
# generator.sh's own cleanup_stale() for skills/agents/rules, scoped to this dir + marker
# convention. Runs unconditionally (even if hook_names was empty this run) so deleting the LAST
# [hooks.*] table still removes every previously generated shim.
if [ -n "$PI_EXTENSIONS_DIR" ] && [ -d "$PI_EXTENSIONS_DIR" ]; then
    for ts_file in "$PI_EXTENSIONS_DIR"/*.ts; do
        [ -f "$ts_file" ] || continue
        is_generated_file "$ts_file" || continue   # never touch hand-written .ts files
        item_name="$(basename "$ts_file" .ts)"
        _is_valid=false
        for _v in "${valid_generated_names[@]:-}"; do
            [ "$_v" = "$item_name" ] && _is_valid=true && break
        done
        if ! $_is_valid; then
            $DRY_RUN || rm "$ts_file"
            $QUIET || echo "  removed stale hook shim: $item_name"
        fi
    done
fi

save_hooks_cache

$QUIET || echo ""
$QUIET || echo "Generated: $generated_count hook shim(s) ($doc_only_count documentation-only)"
