#!/bin/bash
# Zet Scanner — detect dead code, orphaned files, stale references
# Usage: scanner.sh [--json] [--fix]
# Dependencies: bash, grep, find
#
# Checks:
#   1. Orphaned templates — not generating anything (no valid type: field)
#   2. Dead generated files — AUTO-GENERATED marker but no source template
#   3. Orphaned hooks — hook scripts not referenced in any config
#   4. Stale config references — paths in config that don't exist on disk
#   5. Duplicate names — same name across templates
#
# Configuration via environment or zet.toml:
#   ZET_ROOT, ZET_TEMPLATES, ZET_SKILLS, ZET_AGENTS, ZET_RULES
set -eo pipefail

ZET_ROOT="${ZET_ROOT:-$(pwd)}"
ZET_CONFIG="$ZET_ROOT/zet.toml"

read_toml_value() {
    local key="$1" default="$2"
    if [ -f "$ZET_CONFIG" ]; then
        local val
        val=$(grep -E "^${key}\s*=" "$ZET_CONFIG" 2>/dev/null | head -1 | sed 's/^[^=]*=\s*//;s/^"//;s/"$//' | sed "s|^~|$HOME|")
        [ -n "$val" ] && echo "$val" && return
    fi
    echo "$default"
}

TEMPLATE_DIR="${ZET_TEMPLATES:-$(read_toml_value "templates" "$ZET_ROOT/templates")}"
SKILLS_DIR="${ZET_SKILLS:-$(read_toml_value "skills" "$HOME/.claude/skills")}"
AGENTS_DIR="${ZET_AGENTS:-$(read_toml_value "agents" "$HOME/.claude/agents")}"
RULES_DIR="${ZET_RULES:-$(read_toml_value "rules" "$HOME/.claude/rules")}"
HOOKS_DIR="${ZET_HOOKS:-$(read_toml_value "hooks" "$ZET_ROOT/hooks")}"

JSON_MODE=false
FIX_MODE=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --json) JSON_MODE=true; shift ;;
        --fix)  FIX_MODE=true; shift ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# Recognize both Zet and legacy (AUTO-GENERATED) markers for migration support
MARKER_PATTERN="Generated by Zet|AUTO-GENERATED"

get_template_type() {
    local file="$1"
    awk '/^---$/{if(fm){exit}else{fm=1;next}} fm && /^type:/{sub(/^type: */,"");print;exit}' "$file"
}

# --- Collectors ---
declare -a ORPHANED_TEMPLATES=()
declare -a DEAD_SKILLS=()
declare -a DEAD_AGENTS=()
declare -a DEAD_RULES=()
declare -a DUPLICATE_NAMES=()
declare -a ORPHANED_HOOKS=()

# --- 1. Orphaned templates (no valid type) ---
if [ -d "$TEMPLATE_DIR" ]; then
    for file in "$TEMPLATE_DIR"/*_prompt_template.md; do
        [ -f "$file" ] || continue
        type=$(get_template_type "$file")
        if [ -z "$type" ]; then
            ORPHANED_TEMPLATES+=("$(basename "$file")")
        fi
    done
fi

# --- 2. Dead generated files ---
if [ -d "$SKILLS_DIR" ]; then
    for skill_dir in "$SKILLS_DIR"/*/; do
        [ -d "$skill_dir" ] || continue
        name=$(basename "$skill_dir")
        skill_md="$skill_dir/SKILL.md"
        [ -f "$skill_md" ] || continue
        grep -qE "$MARKER_PATTERN" "$skill_md" 2>/dev/null || continue
        template="$TEMPLATE_DIR/${name}_prompt_template.md"
        if [ ! -f "$template" ] || [ "$(get_template_type "$template")" != "skill" ]; then
            DEAD_SKILLS+=("$name")
        fi
    done
fi

if [ -d "$AGENTS_DIR" ]; then
    for agent_file in "$AGENTS_DIR"/*.md; do
        [ -f "$agent_file" ] || continue
        name=$(basename "$agent_file" .md)
        grep -qE "$MARKER_PATTERN" "$agent_file" 2>/dev/null || continue
        template="$TEMPLATE_DIR/${name}_prompt_template.md"
        if [ ! -f "$template" ] || [ "$(get_template_type "$template")" != "agent" ]; then
            DEAD_AGENTS+=("$name")
        fi
    done
fi

if [ -d "$RULES_DIR" ]; then
    for rule_file in "$RULES_DIR"/*.md; do
        [ -f "$rule_file" ] || continue
        name=$(basename "$rule_file" .md)
        grep -qE "$MARKER_PATTERN" "$rule_file" 2>/dev/null || continue
        template="$TEMPLATE_DIR/${name}_prompt_template.md"
        if [ ! -f "$template" ] || [ "$(get_template_type "$template")" != "rule" ]; then
            DEAD_RULES+=("$name")
        fi
    done
fi

# --- 3. Duplicate names ---
if [ -d "$TEMPLATE_DIR" ]; then
    dupes=$(for f in "$TEMPLATE_DIR"/*_prompt_template.md; do
        [ -f "$f" ] || continue
        basename "$f" | sed 's/_prompt_template\.md$//'
    done | sort | uniq -d)

    while IFS= read -r name; do
        [ -n "$name" ] && DUPLICATE_NAMES+=("$name")
    done <<< "$dupes"
fi

# --- 4. Orphaned hooks — scripts in hooks dir not referenced by any config ---
SETTINGS_FILE="${ZET_SETTINGS:-$(read_toml_value "settings" "$ZET_ROOT/settings.json")}"
if [ -d "$HOOKS_DIR" ]; then
    for hook_file in "$HOOKS_DIR"/*.sh; do
        [ -f "$hook_file" ] || continue
        hook_name=$(basename "$hook_file")
        # Check if hook is referenced in settings.json or zet.toml
        referenced=false
        if [ -f "$SETTINGS_FILE" ] && grep -q "$hook_name" "$SETTINGS_FILE" 2>/dev/null; then
            referenced=true
        fi
        if [ -f "$ZET_CONFIG" ] && grep -q "$hook_name" "$ZET_CONFIG" 2>/dev/null; then
            referenced=true
        fi
        if ! $referenced; then
            ORPHANED_HOOKS+=("$hook_name")
        fi
    done
fi

# --- Output ---
TOTAL=$(( ${#ORPHANED_TEMPLATES[@]} + ${#DEAD_SKILLS[@]} + ${#DEAD_AGENTS[@]} + ${#DEAD_RULES[@]} + ${#DUPLICATE_NAMES[@]} + ${#ORPHANED_HOOKS[@]} ))

if $JSON_MODE; then
    to_json() {
        local arr=("$@")
        if [ ${#arr[@]} -eq 0 ]; then echo "[]"; return; fi
        printf '%s\n' "${arr[@]}" | python3 -c "import sys,json; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))"
    }
    python3 - \
        "$(to_json "${ORPHANED_TEMPLATES[@]}")" \
        "$(to_json "${DEAD_SKILLS[@]}")" \
        "$(to_json "${DEAD_AGENTS[@]}")" \
        "$(to_json "${DEAD_RULES[@]}")" \
        "$(to_json "${DUPLICATE_NAMES[@]}")" \
        "$(to_json "${ORPHANED_HOOKS[@]}")" \
        <<'PYEOF'
import json, sys
print(json.dumps({
    "total": sum(len(json.loads(a)) for a in sys.argv[1:]),
    "orphaned_templates": json.loads(sys.argv[1]),
    "dead_skills": json.loads(sys.argv[2]),
    "dead_agents": json.loads(sys.argv[3]),
    "dead_rules": json.loads(sys.argv[4]),
    "duplicate_names": json.loads(sys.argv[5]),
    "orphaned_hooks": json.loads(sys.argv[6]),
}, indent=2))
PYEOF
    exit 0
fi

echo "=== Zet Scan ==="
echo ""

if [ ${#ORPHANED_TEMPLATES[@]} -gt 0 ]; then
    echo "--- Orphaned Templates (no type: field) (${#ORPHANED_TEMPLATES[@]}) ---"
    for item in "${ORPHANED_TEMPLATES[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ ${#DEAD_SKILLS[@]} -gt 0 ]; then
    echo "--- Dead Skills (no source template) (${#DEAD_SKILLS[@]}) ---"
    for item in "${DEAD_SKILLS[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ ${#DEAD_AGENTS[@]} -gt 0 ]; then
    echo "--- Dead Agents (no source template) (${#DEAD_AGENTS[@]}) ---"
    for item in "${DEAD_AGENTS[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ ${#DEAD_RULES[@]} -gt 0 ]; then
    echo "--- Dead Rules (no source template) (${#DEAD_RULES[@]}) ---"
    for item in "${DEAD_RULES[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ ${#DUPLICATE_NAMES[@]} -gt 0 ]; then
    echo "--- Duplicate Names (${#DUPLICATE_NAMES[@]}) ---"
    for item in "${DUPLICATE_NAMES[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ ${#ORPHANED_HOOKS[@]} -gt 0 ]; then
    echo "--- Orphaned Hooks (not referenced in config) (${#ORPHANED_HOOKS[@]}) ---"
    for item in "${ORPHANED_HOOKS[@]}"; do echo "  - $item"; done
    echo ""
fi

if [ "$TOTAL" -eq 0 ]; then
    echo "Clean — no issues detected."
else
    echo "=== $TOTAL issues found ==="
fi
